[UNIONVMS-4619] logbook generation for tripId
UnionVMS/UVMS-ActivityModule-APP pull request #397
Opened 2020-07-31 05:56 UTC by nomikosi

2020-08-06 11:59 UTC, nikospara requested changes

2020-08-06 11:59 UTC, nikospara commented on service/src/main/java/eu/europa/ec/fisheries/ers/service/bean/JasperReportServiceBean.java
> +            InputStream input = getClass().getClassLoader().getResourceAsStream("logbook.jrxml");
Unless you are absolutely certain that some component down the line is actually closing this stream, make sure it is closed:

    try (InputStream input = getClass().getClassLoader().getResourceAsStream("logbook.jrxml")) {
        JasperDesign jasperDesign = JRXmlLoader.load(input);
        ...

2020-08-06 11:59 UTC, nikospara commented on service/src/main/java/eu/europa/ec/fisheries/ers/service/bean/JasperReportServiceBean.java
> +        if(fishingActivityTypeEnum.equals(FishingActivityTypeEnum.JOINT_FISHING_OPERATION) && faCatchTypeEnum.equals(FaCatchTypeEnum.UNLOADED)){
If `fishingActivityTypeEnum == JOINT_FISHING_OPERATION`, then you have returned `CATCHES` from line 826. Is there a logical error here (this is from IntelliJ's inspections).

2020-08-06 11:59 UTC, nikospara commented on service/src/main/java/eu/europa/ec/fisheries/ers/service/bean/JasperReportServiceBean.java
> +        return String.valueOf(df.format(fluxLocationEntity.getLongitude()))+"/"+String.valueOf(df.format(fluxLocationEntity.getLatitude()));
No need for `String.valueOf()` (from IntelliJ's inspections).

2020-08-06 11:59 UTC, nikospara commented on service/src/main/java/eu/europa/ec/fisheries/ers/fa/utils/FishingActivityTypeEnum.java
> +    GEAR_SHOT, GEAR_RETRIEVAL, START_FISHING, JOINED_FISHING_OPERATION, START_ACTIVITY, DISCARD,
Discuss with Leonidas the `JOINT`/`JOINED_FISHING_OPERATION`!

(It seems the correct solution is to drop the `JOINED_FISHING_OPERATION`, replacing it with `JOINT_FISHING_OPERATION`. Make sure the implementation of the logbook works!)

2020-08-06 11:59 UTC, nikospara commented on service/src/main/java/eu/europa/ec/fisheries/ers/service/dto/GearMapperModel.java
> +    public boolean equals(Object o) {
Why aren't you using Lombok for `hashCode`/`equals`?

2020-08-06 12:11 UTC, Georgemanif submitted a review, later dismissed

2020-08-27 08:42 UTC, nikospara approved these changes

2020-08-27 08:43 UTC, merged